### PR TITLE
Allow whitespace inside braces

### PR DESCRIPTION
**Pull request by guillermocalvo**

### CODE REVIEW

**Review by lavoiesl — COMMENTED** [review]
I'm worried that this would end up matching code where double braces would be a thing.

Any reason why you want to allow whitespace?

**Comment by guillermocalvo** [comment]
The regular expressions only match alphanumerical *identifiers* enclosed in double braces (no spaces, colon, or other punctuation characters in between); so no big chance to match actual *code*.

Anyway if the template contains unrelated `{{FOOBAR}}` chunks that are not supossed to be replaced, the only way around it would be assigning `{{FOOBAR={{FOOBAR}}}}` as default value.

The reason I would like to allow whitespace inside braces is because I wanted to reuse some existing templates based on [Liquid](http://shopify.github.io/liquid/basics/introduction/), and those usually contain spaces around identifiers.

A bonus side effect of allowing inner padding of the replaceable identifiers is that it may improve the overall readability of the template.

**Comment by lavoiesl** [comment]
Ok, I’m onboard with this.

I just activated travis-ci (that's why I closed/reopened the PR), can you rebase your branch and modify the example template to incorporate spaces and verify that it works?

**Comment by lavoiesl** [comment]
Awesome, thanks!

**Pull request merged**
